### ISSUE TITLE
Complete Coordination

### ISSUE THREAD

**Issue by drennings** [drennings/MindTheGap#34]
- [x] **Subcategories**
- All subcategories of this dimension should be in the **main diagram**
- When hovering over the subcategories of this dimension, it should show a short **description** of the subcategory (a summary of the introduction of the dimension later on in the paper)
- When hovering over the subcategories of this dimension, it should show an **image**, a suggestive icon (e.g. [this](https://d30y9cdsu7xlg0.cloudfront.net/png/56376-200.png) for team bonding)
- All subcategories of this dimension should be introduced in a neat way

- [x] **Tools**
- All tools of this dimension should be in the **main diagram**
- When hovering over the tools of this dimension, it should show a short **description** of the tool (shorter than the whole piece of text about this tool later on, also this can be the same for github as a coordination tool and github as a cultural tool, since it just briefly describes what github is)
- When hovering over the toolsof this dimension, it should show an **image** (preferably a logo (e.g. the Slack logo) or suggestive icon (e.g. this for [team bonding](https://d30y9cdsu7xlg0.cloudfront.net/png/56376-200.png)) )
- All tools of this dimension should be introduced in a neat way, look at the **comment below**!

**Comment by drennings** [comment]
When describing tools make sure that you touch upon the benefits and drawbacks of the tools, discuss competitors / alternatives and especially introduce why they work good for the purpose we claim it to have! By that, we should be accounting for:

- The idea is good, however especially the second part reads like a load of advertisements.
- I think if there is a comparison between tools, i.e. strength, weakness, price, this deliverable can be a better insight for the reader.
- It is very nice that you mention all the tools. You do have some overlap in tools and well known tools though, but that's unavoidable I guess, because when you do not mention some it is not complete.
- The list is quite comprehensive. however, it would be nice to get insight on how useful these tools actually are. What kinds of tools are best suited for overcoming the common GDSE challenges? Statements like 'Slack may be the best messenger suited for GSE' should also be well reasoned.
- A lot of the content is probably not new for a lot of developers. A lot of the listed tools (e.g. Skype, Slack, Github, Trello) are well known in the developer community, decreasing the usefulness of it towards the Body of Knowledge.
- The list of available tools is nice. However I think the list of tools isn't a very valuable addition to the body of knowledge. There are many other pages that compare and discuss tools of a specific category. To improve the added value to the BoK, I think it would be better to talk about the type of tools that can be used to close a gap. So not so much specific application but more on a global level. For instance explain what a 'screen sharing' application is and why it can be used to lessen a gap. Besides the list of application in the webpage the information on the terms and processes in GDSE could be a bit more explained.

**Comment by drennings** [comment]
Also, add:
-**JIRA** as a tool
-**Automation** as a subcategory

**Comment by drennings** [comment]
You may want to do it like this:

-Work or backlog management

 - [x] JIRA

 - [x] Trello

 - [x] Agile Cockpit

 - [ ] Version One

-Knowledge sharing and collaboration
 - [x] internal wiki pages

 - [ ] Confluence

 - [ ] SharePoint

 - [x] Read The Docs

-Source control and built systems
 - [ ] Bitbucket
 
- [x] GitHub

 - [ ] Visual Studio Online
 
- [x] SonarQube

 - [x] Codefactor

-Hardware
 - [ ] Video conferencing
 - [ ] Overview screens
 - [ ] Private conferencing

**So I would suggest to drop Palantir! It's really an old and ugly tool that nobody uses, but was only published and therefore received some interest**

**Comment by rubenstarmans** [comment]
Eh, @drennings should I completely change the categories in which I describe tools useful for coordination? Not sure if that is a good idea.. Also that last category Hardware seems like it does not belong in coordination but rather in communication.
